import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Smart Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-row bg-slate-200 h-screen overflow-hidden p-5 gap-5">
          <aside className="flex-[0_0_250px] bg-slate-300 rounded-lg p-5 flex flex-col h-full overflow-hidden">
            <Image
              src="/next.svg"
              width={150}
              height={150}
              alt="brand"
              className="mx-auto my-10"
            />
            <ul className="">
              <li>Dashboard</li>
              <li>Menu</li>
            </ul>
            <ul className="mt-auto">
              <li>User</li>
              <li>Logout</li>
            </ul>
          </aside>
          <main className="flex-grow bg-white rounded-lg shadow-xl p-5">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
