import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect, useRouter } from "next/navigation";

export const metadata: Metadata = {
  title: "Smart Menu",
  description: "Generated by create next app",
};

export default async function MenuLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  if (!session || !session.user) {
    redirect("/login");
  }

  return (
    <div className="flex flex-col gap-5 h-full overflow-hidden">
      <h1 className="text-2xl">Menu Management</h1>
      <div className="overflow-hidden">{children}</div>
    </div>
  );
}
